### PR TITLE
Upgrade Github action 'checkout' to v3

### LINKED ISSUE #150: [Security] Workflow ci.yaml is using vulnerable action actions/checkout
The workflow ci.yaml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

### PR DESCRIPTION
**Pull request by dieti80**
Upgrade Github action 'checkout' to v2

- Security fix #150

### CODE REVIEW

**Comment by orltom** [comment]
The install-chart step will not work, because Bitnami has removed all Helm chart versions older than six months from their repository aka index.yaml. For more information see https://github.com/bitnami/charts/issues/10539

Which is a major issue for most projects. Following comment describe a workaround: https://github.com/bitnami/charts/issues/10539#issuecomment-1152641771

**Comment by orltom** [comment]
The new Bitnami Helm Redis Charts are based on Helm 3 which causes an incompatibility issue with our Charts. For that reason I will use the workaround described in https://github.com/bitnami/charts/issues/10539. Temporarily that can be good enough, but for the next Release we need to migrate our Charts to Helm3 and upgrade to a newer Bitnami Helm Redis Chart which is available from the official Bitnami Repository.

**Comment by orltom** [comment]
@dieti80 and @libuweber 
Could you please review the changes. thx

**Review by dieti80 — COMMENTED** [review]
Looks good to me

**Review by libuweber — APPROVED** [review]

**Pull request merged**
